### ISSUE TITLE
[proposal] create a `CodePen` component for interactive code snippets

### ISSUE THREAD

**Issue by katydecorah** [mapbox/dr-ui#101]
CodePen offers prefill embeds: https://blog.codepen.io/documentation/prefill-embeds/

> CodePen Prefill Embeds are designed to render that code for you in a safe and isolated environment to help your users see, understand, and play with it more easily.

I think it would be fun to explore a component that would allow us to transform a code example into an interactive embed. I think this would be great for user adoption, especially on example pages, since the user will essentially be able to fork the code and play around with it.

**Comment by ErinQuinn** [comment]
Love this @katydecorah ❤️
