### ISSUE TITLE
Buttons rendering incorrectly in Safari

### ISSUE THREAD

**Issue by HeyStenson** [mapbox/dr-ui#114]
In Safari, buttons are being rendered as solid blue. On mouseover, the button text does display, albeit very lightly. 

![button_bug](https://user-images.githubusercontent.com/8186438/52509348-a0950200-2bac-11e9-8f35-4e700b20aaef.gif)

**Comment by katydecorah** [comment]
🤦‍♂️ I moved this issue too soon, it _is_ specific to /help. To avoid extra noise, I'll leave here
