### ISSUE TITLE
Rethink how we're theming Notes

### ISSUE THREAD

**Issue by katydecorah** [mapbox/dr-ui#175]
In at least two separate repos, we have components for:
* download-note.js
* legacy-note.js
* warning-note.js
* note.js

I'm wondering if we should audit the types of notes and create themes that automatically include the SVG icon. For example:

Before | After
--|--
```<Note theme="warning" imageComponent={<WarningImage color="orange" />}>This is a legacy product...</Note>``` | ```<Note theme="legacy">This is a legacy product...</Note>```

**Comment by colleenmcginnis** [comment]
Yes @katydecorah! Reducing the number of decisions we have to make at the Markdown file level would be great (with the flexibility to use the generic note layout with any image/color in rare cases).
