### ISSUE TITLE
Create higher-order component to fetch user object

### ISSUE THREAD

**Issue by katydecorah** [mapbox/dr-ui#215]
In all sites we fetch the following information from `MapboxPageShell`:
* Mapbox token (for rendering demos and examples)
* User access token (for display _only_)
* User id (for display _only_)

We should create a higher-order component to fetch this information and wrap it around the page-shell or markdown-page-shell so we can access the data via props.

* https://reactjs.org/docs/higher-order-components.html
* Prior art: https://github.com/mapbox/batfish/blob/1fbac7a634bc80c68b3421de169f618dd381724c/src/webpack/public/with-location.js (withLocation is wrapped around PageShell so that it can pass the location metadata to each page)

This will prevent us from having to make multiple calls to `MapboxPageShell` to fetch this information.

**Comment by danswick** [comment]
Yes!!! Great idea, @katydecorah. 

I wonder if this is a good opportunity for us to explore putting React Hooks to use.

**Comment by danswick** [comment]
The sentry issue linked above is related to empty tokens in JSFiddle / Codepen. This may not be a good place for it, but we could consider it as part of a larger user object / token discussion.
