### ISSUE TITLE
Stop applying `cursor: pointer` to all H2s and H3s

### ISSUE THREAD

**Issue by danswick** [mapbox/dr-ui#221]
As part of https://github.com/mapbox/mapbox-gl-js-docs/pull/91, we noticed that some headings appear to have a very large clickable area in the whitespace surrounding the actual heading text. This can be a confusing signal for users, especially when the page in question requires the click to be on the heading text in order to append the heading to the URL. 

@mapbox/docs does anyone have a strong opinion either way?

**Comment by katydecorah** [comment]
👍 slash it
