### ISSUE TITLE
Add docs build process maybe

### ISSUE THREAD

**Issue by danswick** [mapbox/dr-ui#23]
We could add docs to this project a-la [mr-ui](https://github.com/mapbox/mr-ui/blob/master/README.md#development). @colleenmcginnis -- do you think that would be useful and/or a good thing to prioritize?

**Comment by colleenmcginnis** [comment]
I think it would be helpful to do this at some point, but it's not a high priority right now since I imagine I'll be the primary user of these components in the near-term.
