### ISSUE TITLE
Note icons are tiny in Firefox

### ISSUE THREAD

**Issue by danswick** [mapbox/dr-ui#232]
Note icons are small in Firefox compared to their Chrome comrades. 

![smol](https://user-images.githubusercontent.com/2365503/73021117-caeec800-3ddb-11ea-9d88-20cbfba24681.png)

![chonk](https://user-images.githubusercontent.com/2365503/73021150-df32c500-3ddb-11ea-9574-e4d75006dbe0.png)

**Comment by katydecorah** [comment]
Oh wow, thanks for flagging

**Comment by danswick** [comment]
Oooh here's a clue 🔍. There's no `px` on these inline attributes in FF for some reason 

![image](https://user-images.githubusercontent.com/2365503/73021677-da224580-3ddc-11ea-819c-a896495b6b65.png)
