### ISSUE TITLE
Add automated testing

### ISSUE THREAD

**Issue by danswick** [mapbox/dr-ui#24]
This project does not currently have any automated testing, so all components must be tested manually before publishing. That's probably okay for now while our component count is so low, but will become cumbersome soon. We should add some automated testing once our initial group of components has been added.

**Comment by katydecorah** [comment]
We started adding tests to the Search component. We should make sure to add tests to every new component moving forward. Here's a list of components that still need tests:

* [ ] BackToTopButton
* [ ] BetaFlag
* [ ] CardContainer
* [ ] Card
* [ ] CodeToggle
* [ ] ExamplesPage
* [ ] LevelIndicator
* [ ] NavigationAccordion
* [ ] NavigationDropdown
* [ ] Note
* [ ] OverviewHeader
* [ ] PageLayout
* [ ] ProductMenu
* [x] Search
* [ ] SectionedNavigation
* [ ] ToggleableCodeBlock
* [ ] TopbarSticker
