### ISSUE TITLE
Scroll to active section in NavigationAccordion

### ISSUE THREAD

**Issue by colleenmcginnis** [mapbox/dr-ui#243]
In sites with many items in the NavigationAccordion, it can be disorienting when you open a page that is listed low on the page because you can't see which section is open or any of the `h2` and `h3` headings:

<img width="1121" alt="Screen Shot 2020-02-05 at 10 55 20 AM" src="https://user-images.githubusercontent.com/10479155/73873239-148cd900-4806-11ea-8a2c-97c334945e50.png">

Until you scroll down in the sidebar:

<img width="1120" alt="Screen Shot 2020-02-05 at 10 55 32 AM" src="https://user-images.githubusercontent.com/10479155/73873250-19ea2380-4806-11ea-9b12-0ce0b7f27be6.png">

For pages using `NavigationAccordion`, on page load the sidebar should scroll the active item to the top. 

cc @mapbox/docs

**Comment by katydecorah** [comment]
We should also do this for SectionedNavigation
