### ISSUE TITLE
Close video modal on esc, use black modal frame for RelatedPage video theme

### ISSUE THREAD

**Issue by katydecorah** [mapbox/dr-ui#246]
Capturing feedback from https://github.com/mapbox/documentation/issues/355#issuecomment-583513877

> * Is there a way to fit the 1920 x 1080 dimensions without the white matte on top and bottom (see screen capture below)? (Or maybe just invert the color so there's a black matte with a white x to close.)
> * Is there a way to close the modal if the user hits the esc key?

**Comment by katydecorah** [comment]
> Is there a way to close the modal if the user hits the esc key?

I'm working through these updates now and the esc key to close the modal appears to already be working, @domlet whenever you have a moment can you double check? Thanks!

**Comment by katydecorah** [comment]
Oh wait! @domlet I spoke too soon. The esc key will close the modal, but when you click the play button the focus is on the video and not the modal and so the esc key no longer will close the modal. I'll look into this.

**Comment by domlet** [comment]
Thank you for working on this @katydecorah!

I don't want to create too much work for you :) but I do want to make sure video on docs pages is as unobtrusive as possible. I appreciate your work on this small detail.
