### ISSUE TITLE
Reorganizing the contents of TopBarSticker

### ISSUE THREAD

**Issue by katydecorah** [mapbox/dr-ui#260]
I've been thinking about how we can better organize the contents of TopBarSticker, this ticket contains some ideas.

Also relevant: #259 

## Current problems

- On smaller screens, the navigation wraps:
  - the wrapping doesn't always do so evenly so it can feel a little disconnected
  - the wrapping forces the TopBarSticker to gain height and since it's sticky, takes up more space
- Search takes up a lot of space.

## Ideas to solve: the wrapping navigation

On smaller screens, the tabbed navigation in TopBarSticker wraps:
![image](https://user-images.githubusercontent.com/2180540/75488986-5d582d80-597f-11ea-91f4-f9cf3e3b7d1d.png)

I've been seeing horizontal scrolling on too long navigation across several sites, more recently on: https://developer.twitter.com/en/docs/labs/hide-replies/api-reference/put-hidden

> ![image](https://user-images.githubusercontent.com/2180540/75489224-d6578500-597f-11ea-9cc7-c920df69507c.png)

Stage | Image
----|---
Current | ![image](https://user-images.githubusercontent.com/2180540/75489787-eb80e380-5980-11ea-9f25-c8e1a97a846c.png)
Proposed (draft) | ![image](https://user-images.githubusercontent.com/2180540/75489974-44507c00-5981-11ea-97bd-da3bbd3fd5b9.png)

I'm not sure that I love this solution:
- It feels unusual to essentially hide navigational items, but we could argue that the concept of a hamburger button hides the entirety of a navigation and at least with a scroll you see most of the contents.
- On the subject of hamburger button, I don't think that's an option since the main navigation employs one on smaller devices. Too much burger.
- It also feels like we have dueling scrollbars given the scroll on the sidebar.

I would like to continue to research this and other patterns.

## Ideas to solve: search takes up a lot of space

I wonder if the search button should live in the docs-page-shell.

Stage | Image
---|---
Current | ![image](https://user-images.githubusercontent.com/2180540/75490793-d2793200-5982-11ea-9611-20ffd9587e73.png)
Proposed (draft) | ![image](https://user-images.githubusercontent.com/2180540/75490755-c55c4300-5982-11ea-9f9c-a00a355f5036.png)

A few notes:
- The action of "search" and the product "Search" have an unfortunate name collision, however I think if we styled the action "search" differently we can make the distinction.
- The docs-page-shell has a different build process than our sites, so I'm not sure if there will be any challenges to including component in the page shell.

**Comment by katydecorah** [comment]
I spent a few minutes this morning exploring what it would look like to add search feature to docs-page-shell. I think this is pretty interesting and will require discussion with the team:

The docs-page-shell using JavaScript (not React) so we wouldn't be able to plugin the dr-ui Search component. But this mean that we could use Swiftype's out-of-the-box JavaScript implementation.

### Pros to using Swiftype's out-of-the-box feature

- We no longer have to maintain a search component - To me, this is this biggest pro, especially since the search component caused us to be red one week due to a missed IE11 compatibility. It's really nice when we don't have to worry about maintaining a codebase.
- Implementation is fast and easy.
- The feature includes paginated results.
- Swiftype's search is faster. This is mostly due to the fact that our Search component uses search-as-you-type and we debounce the results to prevent every single letter from being searched.

> ![image](https://user-images.githubusercontent.com/2180540/75559132-f2573700-5a10-11ea-8c23-eefbb3d88b2b.png)
> Draft mock-up of what Swiftype's input could look like in the docs-page-shell (I'd spend more time making it look more Mapbox.)

> ![image](https://user-images.githubusercontent.com/2180540/75559185-03a04380-5a11-11ea-8c0b-95c331346181.png)
> Swiftype's result view modal with paginated results and highlighted description based on search query.
> We would add CSS to make these results and in the input blend with the docs brand better.


### Cons to using Swiftype's out-of-the-box feature

- We lose some customization, for example our current search component's results include content type and code language.
- We lose opportunities to attach Segment tracks, which we currently have enabled on the Search component - however we aren't doing anything with this data at the present.

> ![image](https://user-images.githubusercontent.com/2180540/75559431-73163300-5a11-11ea-940b-30545de6c40e.png)
> Our current search results implementation


## Testing

I pushed a demo of using Swiftype's out-of-the-box search to the /geographic-analytics staging site, but please note that I didn't do much to customize the styles yet, especially around responsive design yet. 

## Impressions

I'm surprised to say this, but I think I like Swiftype's out-of-the-box solution. Having spent a significant amount of time developing the dr-ui Search component, it would be nice to not have to continue to maintain it.

**Comment by colleenmcginnis** [comment]
>I'm surprised to say this, but I think I like Swiftype's out-of-the-box solution.

I also like it! It's clean and I especially like the pagination.

**Comment by katydecorah** [comment]
Adding a note that @colleenmcginnis made a really great proposal in https://github.com/mapbox/documentation/issues/413 to use a dropdown for the main navigation items:

![image](https://user-images.githubusercontent.com/2180540/77672968-f028bf80-6f5f-11ea-84b9-46ef3cd76120.png)

**Comment by katydecorah** [comment]
Building on some of these ideas:

Given the dropdown, we could keep the search on TopBarSticker and remove the button and modal to always show the input:

> ![image](https://user-images.githubusercontent.com/2180540/77677299-dee2b180-6f65-11ea-85bb-da76198acb72.png)

**Comment by katydecorah** [comment]
We'll also want to consider NavigationDropdown which is used as the mobile view for NavigationAccordion:

Image | Image
---|---
![image](https://user-images.githubusercontent.com/2180540/77756736-23be2500-7006-11ea-8c8f-66169b556c54.png) | ![image](https://user-images.githubusercontent.com/2180540/77756744-27ea4280-7006-11ea-93fb-db9d559de66a.png)

NavigationDropdown is a styled select which makes interacting with it a lot easier on mobile devices. Some page would see two dropdown menus on mobile if we move forward with making the TopBarSticker navigation a dropdown.

Things to consider:
- How can we prevent a clash of dropdowns on mobile? Should they be styled the same? Or differently?
- Should TopBarSticker's navigation be a popover on large screens and then a select on smaller screens to make it easier to interact with?

**Comment by katydecorah** [comment]
Regarding the clashing of the navs (NavAccordion + TopBarSticker). For smaller screens, we could consolidate the navigation.

## Larger screens

> ![image](https://user-images.githubusercontent.com/2180540/77793715-ed51cb80-7040-11ea-9b01-c45c5f729730.png)

- No changes to NavigationAccordion at this viewport.
- TopBarSticker navigation is a popover (as we've been discussing adding) and shows the main navigation items and lists all the API reference versions (if that site has them).


## Smaller screens

Image | Image
---|---
![image](https://user-images.githubusercontent.com/2180540/77794157-c5169c80-7041-11ea-915e-e48823deca90.png) | ![image](https://user-images.githubusercontent.com/2180540/77793530-9ea43180-7040-11ea-9316-cc771094335b.png)

- The NavigationDropdown in NavigationAccordion is disabled/removed.
- TopBarSticker's popover is automatically hidden on mobile and replaced by a control select (like Navigation Dropdown). The control select will include the menu items that are found in NavigationAccordion's NavigationDropdown.

**Comment by katydecorah** [comment]
Doing some research and it appears that using `select` element as navigation is not an ideal pattern in terms of accessibility. The `select` element it's meant for input (interacting for forms) and so it changes the scope of the element.

Ref: https://inclusive-components.design/menus-menu-buttons/

There some helpful patterns in the link above that I think we should explore, including this React component: https://github.com/HugoGiraudel/react-menu-button

**Comment by katydecorah** [comment]
Sharing some beautiful fly-out menu design inspo: https://dribbble.com/shots/11052651-Fly-out-menus/attachments/2648852?mode=media
