### ISSUE TITLE
Enable timecode links to change playhead in embedded video player

### ISSUE THREAD

**Issue by domlet** [mapbox/dr-ui#289]
**Is your feature request related to a problem? Please describe.**
Feature request that might require using a different video player than Vimeo. 

**Describe the solution you'd like**
YouTube has a feature that I would like to replicate:
If I mention a time code (ie, `1:37`) in the video description,
YouTube converts it into a hyperlink that sets the playhead of the video at 1:37.

Here's a live example:
https://www.youtube.com/watch?v=57vLd4G4sdY&list=PL86WBCjNmqh7H3syAQQrOWBY5U3DyZvq_&index=4

<img src="https://user-images.githubusercontent.com/6026447/84550752-50f2a900-acc0-11ea-9a5c-3dc8c7080a93.jpg" width=400>

**Describe alternatives you've considered**
I haven't explored this very much, but I'm currently using timecodes without hyperlinks in the tutorials section:

`http://localhost:8080/help/tutorials/customize-label-text-video/`

<img src="https://user-images.githubusercontent.com/6026447/84550860-a4fd8d80-acc0-11ea-934d-5accc0b7b5dd.jpg" width=400>

**Additional context**
Thank you for taking a look at this request!

**Comment by katydecorah** [comment]
This is cool 🌻!

We can use Vimeo's player.js https://github.com/vimeo/player.js#setcurrenttimeseconds-number-promisenumber-rangeerrorerror
