### ISSUE TITLE
Capture referrers in Feedback Sentry issue

### ISSUE THREAD

**Issue by katydecorah** [mapbox/dr-ui#330]
**Is your feature request related to a problem? Please describe.**

Knowing the user's referrer when they submit feedback can be valuable in understanding their path to the page that they have feedback about.

**Describe the solution you'd like**

In the `sendToSentry` function in the `Feedback` component, we add a new tag to capture the referrer, if it exists:

```js
if ('referrer' in document) scope.setTag('referrer', document.referrer); 
```

**Describe alternatives you've considered**

We can get referrer data in Mode, but that requires an extra step to look the feedback up in the database. Having the referrer in the issue tags make the process much faster.

**Additional context**

Ref https://github.com/mapbox/documentation/issues/548

cc @HeyStenson

**Comment by HeyStenson** [comment]
Yesssssss. Thank you @katydecorah!

**Comment by katydecorah** [comment]
We did this in #335!
