### ISSUE TITLE
Add rehype plugin

### ISSUE THREAD

**Issue by colleenmcginnis** [mapbox/dr-ui#34]
In most docs sites we use a rehype plugin that @davidtheclark and I made for the iOS docs to add links to headings in Markdown files ([here it is](https://github.com/mapbox/android-docs/blob/mb-pages/plugins/add-links-to-headings.js) in /android-docs). 

@davidtheclark is this something that would make sense in /dr-ui?

cc @danswick

**Comment by davidtheclark** [comment]
👍
