### ISSUE TITLE
Should we deprecate Glossary components in favor of exampleIndex layout?

### ISSUE THREAD

**Issue by katydecorah** [mapbox/dr-ui#374]
The layout for the Glossary components create a page that's similar to PageLayout's exampleIndex layout. By deprecating the Glossary components and using the exampleIndex for the Glossary page, we can unify the style and experience of cards.

Arguments to consider:

- The exampleIndex layout provides a search title/description feature and a Product dropdown to allow users to filter the glossary items.
- The exampleIndex layout provides a more condensed view of all the glossary cards.
- There are four Glossary components to build the Glossary home page, but they rarely require maintenance.
- The GlossaryCard component is very similar to Card component, but has different hover styles. By choosing the Card component to handle this type of content, we help build a consistent pattern for card-based content.
- The Glossary components add flare and uniqueness to the Glossary page and content.

Current | Proposed 
---|---
![image](https://user-images.githubusercontent.com/2180540/100005951-c3030a00-2d97-11eb-952e-86bb67e6af64.png) | ![image](https://user-images.githubusercontent.com/2180540/100005976-cb5b4500-2d97-11eb-8d30-66df9eb737c0.png)

The transition to using exampleIndex layout would be as quick as changing the layout to `exampleIndex` (and removing the glossary components from the page).

@colleenmcginnis and @danswick this isn't urgent and discussion can definitely happen post-info arch launch, but I would love your thoughts and feedback.

**Comment by danswick** [comment]
This would be fine with me 👍. It would be a big positive to have filters and especially search on the Glossary page.

**Comment by colleenmcginnis** [comment]
You had me at `consistent pattern`. ❤️  I _think_ the filters in the proposed layout would be more helpful to users than the letter-based sections (since terms would still be in alphabetical order).

**Comment by katydecorah** [comment]
Ok, great! I updated the info-arch branch for /help to use exampleIndex and pushed to staging.

I'll leave this issue open until we are able to formally deprecate these components.
