### ISSUE TITLE
Components that could be deprecated post-info arch

### ISSUE THREAD

**Issue by katydecorah** [mapbox/dr-ui#378]
The following components were once core to the PageLayout component, but will be replaced with new systems in #303  

- Topbar
- TopbarSticker
- NavigationDropdown
- SectionedNavigation
- HelpPage

If we feel that these component have run their course and we do not want team members to adopt them in future projects, we should deprecate them.

**Comment by katydecorah** [comment]
@mapbox/docs I would like to remove these (currently) unused components to prohibit further use.

- https://mapbox.github.io/dr-ui/components/#topbar
- https://mapbox.github.io/dr-ui/components/#topbarsticker
- https://mapbox.github.io/dr-ui/components/#navigationdropdown
- https://mapbox.github.io/dr-ui/components/#sectionednavigation
- https://mapbox.github.io/dr-ui/components/#helppage

Does anybody have use case for needing any of the components listed above?

**Comment by colleenmcginnis** [comment]
I support getting rid of these! 🔪

**Comment by domlet** [comment]
Happy retirement to Topbar, TopbarSticker, NavigationDropdown, SectionedNavigation, and HelpPage!

**Comment by katydecorah** [comment]
Fixed in https://github.com/mapbox/dr-ui/pull/407
