### ISSUE TITLE
Style spec nav does not appear (for narrow browser window)

### ISSUE THREAD

**Issue by domlet** [mapbox/dr-ui#403]
**Describe the bug**

The `menu-style-specification` is inaccessible to a user with a narrow display width.

**To Reproduce**

1. narrow your display width (like a skinny window)
1. Go to '...' https://docs.mapbox.com/mapbox-gl-js/style-spec/
2. Make the window bigger (as shown in screenshot below)
3. Notice how the menu doesn't ever appear (see error)
4. Refresh the page with a wider window width
5. Notice how the menu does appear for a wider window after refreshing

![Screen Shot 2021-01-26 at 10 50 16 AM](https://user-images.githubusercontent.com/6026447/105904394-f18aa480-5fd5-11eb-9269-8f5701a41cdb.jpg)

**Expected behavior**

I would want a narrow window to behave like a mobile device, offering the menu but maybe with different styling.

Most importantly I need to be able to access the menu items to experience the bodacious style spec content.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS] mac os 11.1
- Browser [e.g. chrome, safari] chrome 88.0

**Additional context**

Thank you!

**Comment by katydecorah** [comment]
@domlet did you try clicking this:

![image](https://user-images.githubusercontent.com/2180540/105905791-ded19900-5ff0-11eb-89f5-e6234663b735.png)

It's an accordion that collapses on narrower widths to conserve space.

**Comment by domlet** [comment]
Oh wow, I definitely did not notice or click that carat.

I think we may want to make the nav menu items more easily accessible than this. 😬

Maybe introduce a stronger visual signal around that carat to let the user know they are experiencing the `tiny home` display mode?
