### ISSUE TITLE
Sticky sidebar nav vertical overflow problem

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/dr-ui#41]
If the sticky sidebar nav has enough content that it vertically overflows the viewport, there is no way to see the lower content without scrolling to the bottom of the page itself:

![2018-07-27 at 9 47 am](https://user-images.githubusercontent.com/628431/43334425-4e98019c-9182-11e8-803e-aec861d9f976.png)

This is a tricky stickiness bug.

**Comment by colleenmcginnis** [comment]
Hmm it works as expected here: 

![stick-bug](https://user-images.githubusercontent.com/10479155/43487749-69b01d28-94cc-11e8-9a1f-d8a0ebde118f.gif)

I'll try to figure out what we're doing differently between the two.

**Comment by colleenmcginnis** [comment]
This is the result of something I did in the style guide site specifically &mdash; addressing this over there.
