### ISSUE TITLE
Add optional `height` prop to DemoIframe

### ISSUE THREAD

**Issue by katydecorah** [mapbox/dr-ui#505]
The DemoIframe height is not variable:

https://github.com/mapbox/dr-ui/blob/edd33964171631d13ecb41f3fd63d46059d43268/src/components/demo-iframe/demo-iframe.js#L41

We should add a `height` prop and set the default size to `400`.

Use case: https://github.com/mapbox/help/issues/2891

**Comment by malwoodsantoro** [comment]
https://github.com/mapbox/dr-ui/pull/532
