### ISSUE TITLE
Replace code in `GuideGroupIndex` to use CardContainer (with fullWidthCards variant)

### ISSUE THREAD

**Issue by katydecorah** [mapbox/dr-ui#509]
I noticed the pattern for `GuideGroupIndex` in very similar to `CardContainer`, could we swap it to simplify our patterns? What do you think @colleenmcginnis?

Stage | Image
---|---
Current | ![2021-09-17 at 11 58 AM](https://user-images.githubusercontent.com/2180540/133818557-69e4633b-8f32-405a-b1ed-2a346ee2bc53.png) 
Proposed | ![2021-09-17 at 11 58 AM](https://user-images.githubusercontent.com/2180540/133818613-6a9d05dc-9c58-4335-addd-324c03fc0d3e.png)

**Comment by katydecorah** [comment]
Or, should we update CardContainer (fullWidthCards variant) to use the new pattern introduced in `GuideGroupIndex`?

**Comment by colleenmcginnis** [comment]
>What do you think @colleenmcginnis?

Let's use `CardContainer`!
