### ISSUE TITLE
Consistent hover state in product menu trigger

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/dr-ui#51]
![aug-11-2018 09-41-38](https://user-images.githubusercontent.com/628431/43994018-d5b4d6e0-9d4a-11e8-9ac7-cde895a2aac9.gif)

Right now we have a pointing finger and underlined text when hovering over the text, but not when over the arrow. However, *clicking* on the arrow works just the same. It'd be preferable to have the entire clickable area respond in the same way to hover.

**Comment by katydecorah** [comment]
Looks like this got fixed somewhere down the line!
