### ISSUE TITLE
Upgrade mr-ui package to 2.0.0

### ISSUE THREAD

**Issue by tristen** [mapbox/dr-ui#541]
[mr-ui](https://github.com/mapbox/mr-ui) just went through a major rewrite using TypeScript + new internals using https://www.radix-ui.com/. Stubbing this ticket to migrate any used pieces of mr-ui over to the new 2.0.0 version. If this is picked up, an overview of all the changes can be found here: https://github.com/mapbox/mr-ui/blob/main/CHANGELOG.md#200

**Comment by chriswhong** [comment]
Implemented in https://github.com/mapbox/dr-ui/pull/552
