### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/dr-ui#8]
Always gotta rename things at least once!

I realize now that frontend-documentation is potentially pretty confusing, since this isn't documentation about frontend.

How about `@mapbox/documentation-uikit` — which would still leave the door open to non-react things? Or, if @colleenmcginnis feels confident it can be focused on React components, `@mapbox/documentation-components`?

**Comment by colleenmcginnis** [comment]
>which would still leave the door open to non-react things

What kinds of things do you have in mind? 🤔

**Comment by davidtheclark** [comment]
Anything? If you use the same CSS files or JS functions (e.g. a data selector) across these repos, you could share them this way instead of copy-pasting?

**Comment by colleenmcginnis** [comment]
Yes yes. That would be v helpful.

**Comment by danswick** [comment]
An important milestone in this project's lifespan. 

`documentation-uikit` sounds reasonable to me. I would even be ok with shortening it to `docs-uikit` if we feel confident we won't be building any UI tools for PhDs in the near future.

**Comment by colleenmcginnis** [comment]
We're using dr-ui now. 💁
