### ISSUE TITLE
Update bottomBoundaryValue when new docs-page-shell lands

### ISSUE THREAD

**Issue by colleenmcginnis** [mapbox/dr-ui#82]
Just want to note that we'll want to adjust the `bottomBoundaryValue` in the `PageLayout` component when the new docs-page-shell lands. This value determines when the table of contents in the sidebar should unstick at the bottom of the page. That `450` value is specific to the bigger footer that we are currently using in the page shell. The new docs-page-shell will have a much smaller footer so we'll want to adjust. 

https://github.com/mapbox/dr-ui/blob/604ba66258c892372d35a9ca6aefabb5a90abbef/src/components/page-layout/page-layout.js#L27

cc @katydecorah

**Comment by katydecorah** [comment]
Good catch, @colleenmcginnis!
