### ISSUE TITLE
make headings consistent on landing and interior pages

### ISSUE THREAD

**Issue by katydecorah** [mapbox/dr-ui#87]
Noticing that most landing pages have a well-proportioned heading:

![image](https://user-images.githubusercontent.com/2180540/50709976-96289b00-1037-11e9-8a01-1b6744bd9db7.png)

But the interior pages are little larger and different in margin/padding:

![image](https://user-images.githubusercontent.com/2180540/50710005-b5bfc380-1037-11e9-8da6-fc06b9d90490.png)

Ideally, these headings should have the same size and spacing.

**Comment by colleenmcginnis** [comment]
Yes! 🏆 🙌

**Comment by katydecorah** [comment]
I think this can be fixed with the help of https://github.com/mapbox/dr-ui/pull/91 and making sure h1s are children of `#docs-pages .prose`

**Comment by katydecorah** [comment]
This is happening in each repo by moving the h1 to markdownpageshell along with the dr-ui 0.5.0 update
